<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>_hyperscript</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>comment.line.double-dash._hyperscript</string>
        <key>begin</key>
        <string>--</string>
        <key>end</key>
        <string>$</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#possessive</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#attributeRefs</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#punctuation</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#simpleLiterals</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#cssRefs</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#inlineJS</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>possessive</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator._hyperscript</string>
            <key>match</key>
            <string>(?x) \+ | (?&lt;=\s) - (?=\s) | \/ | \* | \\ | -&gt; | &lt;(?= \s) | &gt; | &lt;= | &gt;= | == | = | !== | != | =| \.\. | (?&lt;=[A-Za-z0-9\}\)\]]) \. | \% | \| | ! | \$ | 's</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>name</key>
        <string>keyword._hyperscript</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control._hyperscript</string>
            <key>match</key>
            <string>(?x) \b(
  catch|if|else|otherwise
  repeat\s+forever|repeat\s+for|repeat\s+in|repeat\s+while|
  repeat\s+until\s+event|repeat\s+until|repeat|times|
  then|end|while|until|unless|for
)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.command._hyperscript</string>
            <key>match</key>
            <string>(?x) \b(
  add|remove|put|async|call|get|hide|measure|add|async|call|get|hide|measure|
  return|send|settle|set|show|take|throw|toggle\s+between|toggle|
  transition|trigger|wait\s+for|wait|fetch|tell|go|increment|
  decrement|halt|make\s+an|make\s+a|make|log|default|continue|breakpoint
)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.feature._hyperscript</string>
            <key>match</key>
            <string>(?x) \b(
  on|def|worker|eventsource|socket|init|behavior|install|require
)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.expression._hyperscript</string>
            <key>match</key>
            <string>(?x) \b(
  in|from|to|with|over|into|before|after|
  at\s+end\s+of|at\s+start\s+of|is\s+an|is\s+a|is\s+not|
  is|am|as|and|or|no|closest|the|of|first|last|random|on|
  seconds|milliseconds|(?&lt;=\s)s|(?&lt;=\s)ms)\b|
  (?&lt;=on\s)every|(debounced|throttled) \s+ at|
  queue|(?&lt;=queue\s)(all|first|last|none)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.modifier._hyperscript</string>
            <key>match</key>
            <string>\b(local|element|module|global)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.language._hyperscript</string>
            <key>match</key>
            <string>(?x) \b(
  I|me|my|you|your|yourself|it|its|result|
  event|target|detail|
  document|body
)\b</string>
          </dict>
        </array>
      </dict>
      <key>punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.separator.comma._hyperscript</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.key-value._hyperscript</string>
            <key>match</key>
            <string>:</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.brace.round._hyperscript</string>
            <key>match</key>
            <string>[()]</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.brace.square._hyperscript</string>
            <key>match</key>
            <string>[\[\]]</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double._hyperscript</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inside-string</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.single._hyperscript</string>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#inside-string</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.interpolated._hyperscript</string>
            <key>begin</key>
            <string>`</string>
            <key>end</key>
            <string>`</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#template</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>inside-string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape._hyperscript</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>template</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.template.expression._hyperscript</string>
            <key>begin</key>
            <string>\$\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source._hyperscript</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>simpleLiterals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric._hyperscript</string>
            <key>match</key>
            <string>\d+(\.\d+)?</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language._hyperscript</string>
            <key>match</key>
            <string>\b(true|false|null|undefined)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.variable._hyperscript.builtin-conversion</string>
            <key>match</key>
            <string>(?x) \b(
  # Conversions
  String|Number|Int|Float|Date|Array|HTML|Fragment|JSON|Object|Values
)\b'</string>
          </dict>
        </array>
      </dict>
      <key>cssRefs</key>
      <dict>
        <key>name</key>
        <string>meta.selector._hyperscript</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.selector._hyperscript entity.other.attribute-name.class._hyperscript</string>
            <key>match</key>
            <string>(?x) \.[\-\w\d_\$]+</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.selector._hyperscript entity.other.attribute-name.id._hyperscript</string>
            <key>match</key>
            <string>(?x) \#[\-\w\d_\$]+</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.selector._hyperscript entity.other.attribute-name.class._hyperscript.dynamic-class</string>
            <key>begin</key>
            <string>(?&lt;![A-Za-z0-9\}\)\]])\.\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.selector._hyperscript entity.other.attribute-name.id._hyperscript.dynamic-class</string>
            <key>begin</key>
            <string>(?&lt;![A-Za-z0-9\}\)\]])\#\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.embedded.line.css meta.selector._hyperscript</string>
            <key>contentName</key>
            <string>source.css</string>
            <key>begin</key>
            <string>\&lt;(?!\s)</string>
            <key>end</key>
            <string>\/\&gt;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#template</string>
              </dict>
              <dict>
                <key>include</key>
                <string>source.css#selector-innards</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>inlineJS</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.embedded.line.js</string>
            <key>begin</key>
            <string>\b(js)\b(\(.*\))?</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.command._hyperscript</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\bend\b</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.other.command._hyperscript</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>attributeRefs</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.attribute._hyperscript.long-form</string>
            <key>begin</key>
            <string>\[@([a-zA-Z\-\_]+)</string>
            <key>end</key>
            <string>]</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name._hyperscript</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>punctuation.separator.key-value._hyperscript</string>
                <key>match</key>
                <string>\=</string>
              </dict>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-value</string>
                <key>begin</key>
                <string>(?&lt;=\=)</string>
                <key>end</key>
                <string>(?=\])</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#strings</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.attribute._hyperscript</string>
            <key>match</key>
            <string>@([a-zA-Z\-\_]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.other.attribute-name._hyperscript</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source._hyperscript</string>
  </dict>
</plist>